version: "3.5"

services:
    inki:
        build:                               
          context: .
          dockerfile: Dockerfile--rvm-solution
      # restart: always
      # env_file:
      #   - inki_db.env
        environment:
          - PROJECT_ROOT="/var/www/inki/"
          - RAILS_ENV=development
        working_dir: /var/www/inki/ 
      # TODO: set locale in container
        user: rvm
      # command: tail -f /etc/passwd  # do nothing but keep container alive (for testing)
      # command: bash -l -c "bundle exec rails server -p 3000 -b 0.0.0.0"
        command: bash -c "./entrypoint.bash"
        ports:
          - 3000:3000
      # l.b. could be used to map src files directly into container
      # currently, inki source code is copied into container while building the image
      # volumes:
      #   - .:/var/www/inki/
        networks:
          - inki
          - traefik
      # labels:
      # # TODO: enable traefik
      #     - "traefik.frontend.rule=Host:fk_inki.fkome.local"
      #     - "traefik.frontend.entryPoints=http,https"
      #     - "traefik.docker.network=traefik"
      #     - "traefik.port=3000"


    inki_db:
        image: postgres:11.2
      # restart: always
        env_file:
          - inki_db.env
        volumes:
          - inki_db_volume:/var/lib/postgresql/data
        networks:
          - inki
        labels:
          - "traefik.enable=false"

networks:
  inki:
  traefik:
    name: traefik

volumes:
  inki_db_volume:
