# Important: Indentations matter! please use SPACES to indent your fields, otherwhise this won't work.
development:
  # global configuration
  :global: # IMPORTANT: the leading colon is not a typo!
    :verboselevel: 5 # 0-5 0... no debug 5... all debug
    :sluggishness: 1 # the time in seconds the dispatcher waits until it actually starts a dispatch.
    :concurrent_items: 100 # the items that are concurrently inspected by the dispatcher (a limit while searching the dispatch_jobs table)
    :sleepinterval: 10 # the time in seconds the daemon sleeps until it checks the database again. 
    :remove_done_jobs_after: 1 # the time in days the daemon will remove done jobs.
    :base_url: https://inki.wogri.at # the base URL of your installation. this is used when sending out e-mails
    :mail_to: wogri@wogri.com
  
  :dispatches:
    ldap.wogri.at:
      :ldap:
        :lifetime: 10 # can take up to 30 seconds
        :interested_in_objects: # is only executed when the following objects are dispatched
        - user_accounts
        - user_mail_addresses
        - user_rights
        - user_mail_settings
        - user_web_settings
        - user_spamassassin_settings
        :ldap:
          :host: ldap.wogri.at
          :port: 389
          :auth:
            :method: :simple
            :username: cn=admin,dc=wogri,dc=at
            :password: cR5sl2t
          :base: dc=wogri,dc=at
        :ldap_user_tree: ou=People,o=wogriAtUsers
        :ldap_group_tree: ou=Groups,o=wogriAtUsers
        :mail_to: wogri@wogri.com
  
    localhost:
      :inki_doc:
        :lifetime: 10 # can take up to 30 seconds
        :interested_in_objects: # is only executed when the following objects are dispatched
        - inki_docs
