users:
  user_accounts: :write
  user_homepages: :read
  startpages: :read
  users: :read
http_basic:
  users: :write
  user_accounts: :read
accounting:
  participants: :write
  startpages: :read
read_only:
  :all: :read
admins:
  :all: :write

