- my_company:
  - time_elements
  - projects
  - customers
  - bills
  - expenses:
    - expenses
    - rides
- wogri_at_system:
  - user_accounts
  - group_accounts
  - user_mail_addresses
  - user_homepages
  - network_components
  - ip_addresses
- various_data:
  - bookmarks
  - bookmark_categories
  - ipv6_routes
  - jabber_message_archives
  - delayed_mails
  - weather_forecasts
  - inki_docs
  - fh:
    - exam_questions
    - courses
    - question_difficulties
- internal:
  - dispatch_jobs
  - colors
  - rgbs
  - users
  - usergroups
  - dropdown_fields:
    - rights
    - webserver_templates
    - bill_templates
    - network_component_types
    - snmp_pollers
